name: Configura deploy GitHub Pages

on:
  push:
    branches:
      - main

# 1. I PERMESSI SONO OBBLIGATORI per evitare l'errore "Not Found"
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v5

      # 2. CARICA SOLO I FILE DELLA PWA FLUTTER GENERATI SU WEB
      - name: Carica l'artefatto
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

      # 3. PUBBLICA IL SITO
      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
